#!/usr/bin/env bash
# mise description="Create Kubernetes Kind Cluster with Registry Caches"
# mise outputs=[".mise/kubeconfig.yaml"]
# mise depends=["kind:install:docker-registry", "kind:install:docker-cache"]

set -o errexit

scriptDir=$(dirname -- "$(readlink -f -- "$BASH_SOURCE")")

## Create Kind Cluster
# If cluster already exists, `exit 0`
kind get clusters | grep -q ${KIND_CLUSTER_NAME} && exit 0

kind create cluster --config ${scriptDir}/kind.yaml --name ${KIND_CLUSTER_NAME}
kind get kubeconfig --name ${KIND_CLUSTER_NAME} > $(pwd)/.mise/kubeconfig.yaml
chmod 600 $(pwd)/.mise/kubeconfig.yaml
KUBECONFIG=$(pwd)/.mise/kubeconfig.yaml

# Switch to the new cluster
kubectl config use-context ${KIND_K8S_CONTEXT}
kubectl create namespace cloudapi
kubectl label namespace cloudapi istio-injection=enabled
kubectl config set-context --current --namespace=cloudapi

## Setup local docker registry and caches
# https://kind.sigs.k8s.io/docs/user/local-registry/
# 1. Create registry container unless it already exists
## Done in `kind:install:registry`

# Create Docker Cache
## Done in `kind:install:pull-through`
# Connect the cache to the cluster network
docker network connect "kind" "${KIND_DOCKER_CACHE}" || true

# 2. Create kind cluster with containerd registry config dir enabled
# Handled in `kind.yaml`

# 3. Add the registry configs to the nodes
REGISTRY_DIR="/etc/containerd/certs.d"
CACHE_SETUP_URL=http://${KIND_DOCKER_CACHE}:3128/setup/systemd
MAX_RETRIES=10
RETRY_INTERVAL=1

for node in $(kind get nodes --name ${KIND_CLUSTER_NAME}); do
  # Main registry
  docker exec "${node}" mkdir -p "${REGISTRY_DIR}/localhost:${KIND_DOCKER_REGISTRY_PORT}"
  cat <<EOF | docker exec -i "${node}" cp /dev/stdin "${REGISTRY_DIR}/localhost:${KIND_DOCKER_REGISTRY_PORT}/hosts.toml"
[host."http://${KIND_DOCKER_REGISTRY}:5000"]
EOF

  # Cache registries
  retry_count=0
  while [ $retry_count -lt $MAX_RETRIES ]; do
    if docker exec "${node}" curl -s -f ${CACHE_SETUP_URL} > /dev/null; then
      docker exec "${node}" bash -c "\
        curl -s ${CACHE_SETUP_URL} \
        | sed s/docker\.service/containerd\.service/g \
        | sed '/Environment/ s/$/ \"NO_PROXY=127.0.0.0\/8,10.0.0.0\/8,172.16.0.0\/12,192.168.0.0\/16\"/' \
        | bash"
      echo "Successfully set up cache for node ${node}"
      break
    else
      retry_count=$((retry_count + 1))
      if [ $retry_count -eq $MAX_RETRIES ]; then
        echo "Failed to set up cache for node ${node} after ${MAX_RETRIES} attempts"
      else
        echo "Attempt ${retry_count} failed. Retrying in ${RETRY_INTERVAL} second(s)..."
        sleep ${RETRY_INTERVAL}
      fi
    fi
  done
done

# 4. Connect the registries to the cluster network
docker network connect "kind" "${KIND_DOCKER_REGISTRY}" || true

# 5. Document the local registry
# https://github.com/kubernetes/enhancements/tree/master/keps/sig-cluster-lifecycle/generic/1755-communicating-a-local-registry
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: local-registry-hosting
  namespace: kube-public
data:
  localRegistryHosting.v1: |
    host: "localhost:${KIND_DOCKER_REGISTRY_PORT}"
    help: "https://kind.sigs.k8s.io/docs/user/local-registry/"
EOF
