import os

from fastapi import FastAPI

from shared.constants import PROJECT_VERSION
from shared.log_config import get_logger

logger = get_logger(__name__)


def create_app() -> FastAPI:
    openapi_name = os.getenv(
        "OPENAPI_NAME", "Aries Cloud API: Webhooks and Server-Sent Events"
    )

    application = FastAPI(
        title=openapi_name,
        description="""
        Welcome to the OpenAPI interface for the Aries Cloud API Webhooks and Server-Sent Events (SSE).
        This API enables the management and processing of webhook events generated by ACA-Py instances.
        It supports filtering and forwarding events to subscribers based on topic and wallet ID,
        as well as handling Server-Sent Events (SSE) for real-time communication with clients.
        """,
        version=PROJECT_VERSION,
    )

    return application


logger.info("Start webhooks server")
app = create_app()


@app.get("/health")
async def health_check():
    return {"status": "healthy"}
