#!/usr/bin/env bash
# mise description="Start up the Docker Pullthrough Cache"

# 'gcr.io' seems to have issues when run in Github Actions
# https://github.com/rpardini/docker-registry-proxy/issues/115
registries="quay.io ghcr.io registry.k8s.io"

# Create cache directories
mkdir -p $(pwd)/tilt/docker/cache $(pwd)/tilt/docker/certs

# Create resolver config
echo "resolver 1.1.1.1 ipv6=off;" > $(pwd)/tilt/docker/resolvers.conf

# Create cache container
if ! docker container ls -a --format '{{.Names}}' | grep -q "^${KIND_DOCKER_CACHE}$"; then
  docker run -d --name ${KIND_DOCKER_CACHE} \
    -p 0.0.0.0:3128:3128 \
    -e ENABLE_MANIFEST_CACHE=true \
    -e REGISTRIES="${registries}" \
    --hostname ${KIND_DOCKER_CACHE} \
    -v $(pwd)/tilt/docker/cache:/docker_mirror_cache \
    -v $(pwd)/tilt/docker/certs:/ca \
    -v $(pwd)/tilt/docker/resolvers.conf:/etc/nginx/resolvers.conf \
    ghcr.io/rpardini/docker-registry-proxy:0.6.4-debug
fi

# Start cache container if not running
if [ "$(docker inspect -f '{{.State.Running}}' ${KIND_DOCKER_CACHE} 2>/dev/null || true)" != 'true' ]; then
  docker start ${KIND_DOCKER_CACHE}
fi
