#!/usr/bin/env bash
# mise description="Install Ingress Nginx in Kubernetes"
# mise depends=["kind:create"]

# Ensure we are on the right kube context
kubectl config use-context ${KIND_K8S_CONTEXT}

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx --force-update
helm repo update

# Install Nginx Ingress
# https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
helm upgrade \
  --install \
  ingress-nginx \
  --namespace ingress-system \
  --create-namespace \
  --values ./tilt/ingress_nginx/values.yaml \
  --wait \
  --timeout 300s \
  ingress-nginx/ingress-nginx \
  --version 4.12.0
