#!/usr/bin/env bash
# mise description="Install Ingress Nginx in Kubernetes"
# mise depends=["kind:create"]
# mise env={KUBECONFIG = ".mise/kubeconfig.yaml"}

kindClusterName=kind-aries-cloudapi

# Ensure we are on the right kube context
kubectl config use-context ${kindClusterName}

helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
helm repo update

# Install Nginx Ingress
# https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
helm upgrade \
  --install \
  ingress-nginx \
  --namespace ingress-system \
  --create-namespace \
  --values ./tilt/ingress_nginx/values.yaml \
  --wait \
  --timeout 300s \
  ingress-nginx/ingress-nginx \
  --version 4.11.2
