#!/usr/bin/env bash
# mise description="Start up the Docker Pullthrough Cache"

cache_name='cache-docker'
registries="quay.io ghcr.io registry.k8s.io gcr.io"

# Create cache directories
mkdir -p $(pwd)/tilt/docker/cache $(pwd)/tilt/docker/certs

# Create resolver config
echo "resolver 1.1.1.1 ipv6=off;" > $(pwd)/tilt/docker/resolvers.conf

# Create cache container
if [ "$(docker inspect -f '{{.State.Running}}' "${cache_name}" 2>/dev/null || true)" != 'true' ]; then
  docker run -d --name ${cache_name} \
    -p 0.0.0.0:3128:3128 \
    -e ENABLE_MANIFEST_CACHE=true \
    -e REGISTRIES="${registries}" \
    --hostname ${cache_name} \
    -v $(pwd)/tilt/docker/cache:/docker_mirror_cache \
    -v $(pwd)/tilt/docker/certs:/ca \
    -v $(pwd)/tilt/docker/resolvers.conf:/etc/nginx/resolvers.conf \
    ghcr.io/rpardini/docker-registry-proxy:0.6.4-debug
fi
