#!/usr/bin/env bash
# mise description="Start up the local Kind Docker Registry"

## Setup local docker registry and caches
# https://kind.sigs.k8s.io/docs/user/local-registry/
reg_name='kind-registry'
reg_port='5001'

# Create main registry
if [ "$(docker inspect -f '{{.State.Running}}' "${reg_name}" 2>/dev/null || true)" != 'true' ]; then
  docker run \
    -d --restart=always -p "127.0.0.1:${reg_port}:5000" --network bridge --name "${reg_name}" \
    registry:2
fi
