replicaCount: 1

strategy:
  type: Recreate

daemon: false

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m

image:
  repository: "324190738845.dkr.ecr.af-south-1.amazonaws.com/ledger-browser"
  pullPolicy: Always
  tag: "pr-8"

ingress:
  internal:
    enabled: true
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: ledger-browser.cloudapi.dev.didxtech.com
        paths:
          - path: /
            port: 9000
  external:
    enabled: false

service:
  hostNetwork: false
  port: 9000
  containerPort: 8000
  appProtocol: tcp

command:
  - "bash"
  - "-c"
  - "export DOCKERHOST=ledger-nodes; ./scripts/start_webserver.sh"

httpProbes:
  liveness:
    path: /status/text
    initialDelaySeconds: 30
    # timeoutSeconds: 30
  readiness:
    type: httpGet
    path: /status/text
    # initialDelaySeconds: 5
    timeoutSeconds: 5
    periodSeconds: 10

env:
  MAX_FETCH: "50000"
  RESYNC_TIME: "120"
  REGISTER_NEW_DIDS: "True"
  LEDGER_INSTANCE_NAME: "localhost"
  LOG_LEVEL: info
  LEDGER_SEED: 000000000000000000000000Trustee1
