replicaCount: 1

daemon: false

podAnnotations:
  sidecar.istio.io/proxyCPU: 10m

strategy:
  type: Recreate

image:
  repository: "324190738845.dkr.ecr.af-south-1.amazonaws.com/tails-server"
  pullPolicy: Always
  tag: "1.0.0"

ingress:
  internal:
    enabled: true
    className: nginx-internal
    annotations:
      nginx.ingress.kubernetes.io/service-upstream: "true"
    hosts:
      - host: tails-server.cloudapi.dev.didxtech.com
        paths:
          - path: /
            port: 6543
  external:
    enabled: false

args:
  - tails-server
  - --host
  - 0.0.0.0
  - --storage-path
  - ./tails-server-db
  - --log-level
  - INFO

service:
  port: 6543
  containerPort: 6543
  appProtocol: tcp

persistence:
  enabled: true
  mountPath: /home/indy/tails-server-db
  capacity: 10Gi
  storageClassName: "gp3"

podSecurityContext:
  fsGroup: 1001
