FROM ghcr.io/hyperledger/aries-cloudagent-python:py3.9-0.11.0

USER root

# Install wallet group id plugin
RUN pip3 install --no-cache-dir acapy-wallet-groups-plugin==0.6.2

# install redis-events plugin
RUN pip3 install git+https://github.com/didx-xyz/aries-acapy-plugins@v1-2024-02-28#subdirectory=redis_events

COPY scripts/startup.sh startup.sh
RUN chmod +x ./startup.sh

USER aries

ENTRYPOINT [ "./startup.sh" ]
CMD [ "--wallet-type", "askar", "--auto-promote-author-did", \
  "--plugin", "acapy_wallet_groups_plugin", \
  "--plugin", "redis_events.v1_0.redis_queue.events", "--plugin-config-value", "redis_queue.connection.connection_url=\"redis://172.29.0.101:6377\""]
