FROM ghcr.io/hyperledger/aries-cloudagent-python:py3.12-1.0.0rc4

USER root
# install redis-events plugin
RUN pip3 install git+https://github.com/didx-xyz/aries-acapy-plugins@v1-2024-07-11#subdirectory=redis_events

COPY scripts/startup.sh startup.sh
RUN chmod +x ./startup.sh

USER aries

ENTRYPOINT [ "./startup.sh" ]
CMD [ "--wallet-type", "askar", \
  "--plugin", "redis_events.v1_0.redis_queue.events", "--plugin-config-value", "redis_queue.connection.connection_url=\"redis://172.29.0.101:6377\""]
