FROM ghcr.io/didx-xyz/aries-cloudagent-bbs:py3.12-1.0.0b1

USER root

# Install redis-events plugin
RUN pip install --no-cache-dir git+https://github.com/didx-xyz/aries-acapy-plugins@v1-2024-08-30#subdirectory=redis_events

# Install Google Protobuf
ARG PROTOBUF_VERSION=5.28.1
RUN pip install --no-cache-dir protobuf==${PROTOBUF_VERSION}

COPY scripts/startup.sh startup.sh
RUN chmod +x ./startup.sh

USER aries

ENTRYPOINT [ "./startup.sh" ]
CMD [ "--wallet-type", "askar", \
  "--plugin", "redis_events.v1_0.redis_queue.events", "--plugin-config-value", "redis_queue.connection.connection_url=\"redis://172.29.0.101:6377\""]
