FROM bcgovimages/von-image:py36-1.16-1

USER root
RUN apt-get update
RUN apt-get update && apt-get install -y gcc

RUN pip3 install aries-cloudagent[askar]==0.8.0 acapy-wallet-groups-plugin

ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
COPY scripts/startup.sh startup.sh
RUN chmod +x ./startup.sh
# COPY scripts/ngrok-wait.sh wait.sh
# RUN chmod +x ./wait.sh

USER $user

CMD ./startup.sh --wallet-type askar --auto-promote-author-did --plugin acapy_wallet_groups_plugin
