FROM ghcr.io/didx-xyz/acapy-agent-bbs:py3.12-1.1.1b5

USER root

# Install Google Protobuf
ARG PROTOBUF_VERSION=5.29.0
RUN pip install --no-cache-dir protobuf==${PROTOBUF_VERSION}

# install nats-events plugin
RUN pip install --no-cache-dir git+https://github.com/didx-xyz/aries-acapy-plugins@test-1.1.1b5#subdirectory=nats_events

COPY scripts/startup.sh startup.sh
RUN chmod +x ./startup.sh

USER aries

ENTRYPOINT [ "./startup.sh" ]
CMD [ "--wallet-type", "askar", \
  "--plugin", "nats_events.v1_0.nats_queue.events", "--plugin-config-value", "nats_queue.connection.connection_url=\"nats://nats-1:4222\""]
