import logging
import os
from typing import Container

from fastapi import FastAPI

from webhooks.dependencies import sse_manager
from webhooks.dependencies.container import get_container
from webhooks.routers import sse, webhooks

LOG_LEVEL = os.getenv("LOG_LEVEL", "warning")
LOGGER = logging.getLogger(__name__)


def create_app() -> FastAPI:
    init_container()

    OPENAPI_NAME = os.getenv(
        "OPENAPI_NAME", "Aries Cloud API: Webhooks and Server-Sent Events"
    )
    PROJECT_VERSION = os.getenv("PROJECT_VERSION", "0.1.0")

    app = FastAPI(
        title=OPENAPI_NAME,
        description="""
        Welcome to the OpenAPI interface for the Aries Cloud API Webhooks and Server-Sent Events (SSE).
        This API enables the management and processing of webhook events generated by ACA-Py instances. 
        It supports filtering and forwarding events to subscribers based on topic and wallet ID,
        as well as handling Server-Sent Events (SSE) for real-time communication with clients.
        """,
        version=PROJECT_VERSION,
    )

    app.include_router(webhooks.router)
    app.include_router(sse.router)

    return app


def init_container() -> Container:
    container = get_container()
    container.wire(modules=[__name__, sse_manager, webhooks])
    return container


app = create_app()
